select COLUMN_NAME, 
CONSTRAINT_NAME, 
REFERENCED_COLUMN_NAME, 
REFERENCED_TABLE_NAME 
from information_schema.KEY_COLUMN_USAGE 
where TABLE_NAME = 'l10n_text_resource';

SELECT TABLE_NAME,
COLUMN_NAME,
CONSTRAINT_NAME, 
REFERENCED_TABLE_NAME,
REFERENCED_COLUMN_NAME 
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
WHERE REFERENCED_TABLE_NAME = 'l10n_text_resource';

select count(*) from l10n_text_resource;

